import { TurmaDataInicial } from "../types";

export const turmasJson: TurmaDataInicial[] = [
  {
    codigo: "5500004",
    nome: "Fundamentos em Ciências de Dados",
    curso: "BCDados",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=5500004",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Qui.",
        inicio: "14:20",
        fim: "16:00",
      },
    ],
    id: "5500004,1",
    conflitos: [
      "SME0340,4",
      "SME0346,1",
      "SME0340,5",
      "SME0320,3",
      "SME0860,1",
      "SME0121,1",
      "SME0216,1",
      "SME0221,1",
      "SME0104,2",
      "SME0341,2",
    ],
    noturna: false,
  },
  {
    codigo: "EST5101",
    nome: "Teoria das Probabilidades",
    curso: "PIPGes",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=EST5101",
    nivel: "p",
    horarios: [],
    id: "EST5101,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "EST5102",
    nome: "Inferência Estatística",
    curso: "PIPGes",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=EST5102",
    nivel: "p",
    horarios: [],
    id: "EST5102,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "EST5104",
    nome: "Inferência Bayesiana",
    curso: "PIPGes",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=EST5104",
    nivel: "p",
    horarios: [],
    id: "EST5104,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "EST5105",
    nome: "Tópicos de Pesquisa I",
    curso: "PIPGes",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=EST5105",
    nivel: "p",
    horarios: [],
    id: "EST5105,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "EST5108",
    nome: "Sistemas Complexos",
    curso: "PIPGes",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=EST5108",
    nivel: "p",
    horarios: [],
    id: "EST5108,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "EST5519",
    nome: "Capacitação Docente em Estatística I",
    curso: "PIPGes",
    turma: 1,
    carga: 0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=EST5519",
    nivel: "p",
    horarios: [],
    id: "EST5519,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "EST5522",
    nome: "Teoria da Decisão",
    curso: "PIPGes",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=EST5522",
    nivel: "p",
    horarios: [],
    id: "EST5522,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "EST5534",
    nome: "Aprendizado de Máquina Estatístico",
    curso: "PIPGes",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=EST5534",
    nivel: "p",
    horarios: [],
    id: "EST5534,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "EST5801",
    nome: "Probabilidade Avançada",
    curso: "PIPGes",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=EST5801",
    nivel: "p",
    horarios: [],
    id: "EST5801,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "EST5805",
    nome: "Tópicos Avançados de Pesquisa II",
    curso: "PIPGes",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=EST5805",
    nivel: "p",
    horarios: [],
    id: "EST5805,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "SLC0609",
    nome: "Álgebra Linear e Equações Diferenciais",
    curso: "Lic. Ciências Exatas",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SLC0609",
    nivel: "g",
    horarios: [
      {
        dia: "Sex.",
        inicio: "19:00",
        fim: "20:40",
      },
      {
        dia: "Sex.",
        inicio: "21:00",
        fim: "22:40",
      },
    ],
    id: "SLC0609,1",
    conflitos: [
      "SME0520,1",
      "SME0806,1",
      "SME0892,1",
      "SME0821,1",
      "SME0803,1",
    ],
    noturna: true,
  },
  {
    codigo: "SME0104",
    nome: "Cálculo Numérico",
    curso: "BCC",
    turma: 2,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0104",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Qui.",
        inicio: "08:10",
        fim: "09:50",
      },
    ],
    id: "SME0104,2",
    conflitos: [
      "SME0300,2",
      "SME0340,4",
      "SME0333,1",
      "SME0860,1",
      "SME0205,1",
      "SME0121,1",
      "SME0221,1",
      "SME0620,1",
      "5500004,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0104",
    nome: "Cálculo Numérico",
    curso: "BCC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0104",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Qui.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0104,1",
    conflitos: [
      "SME0340,4",
      "SME0341,1",
      "SME0121,2",
      "SME0340,2",
      "SME0205,1",
      "SME0221,1",
      "SME0620,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0121",
    nome: "Processos Estocásticos",
    curso: "BCC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0121",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Qui.",
        inicio: "08:10",
        fim: "09:50",
      },
    ],
    id: "SME0121,1",
    conflitos: [
      "SME0300,2",
      "SME0340,4",
      "SME0333,1",
      "SME0860,1",
      "SME0205,1",
      "SME0221,1",
      "SME0620,1",
      "SME0104,2",
      "5500004,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0121",
    nome: "Processos Estocásticos",
    curso: "BCC, BCDados",
    turma: 2,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0121",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Qui.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0121,2",
    conflitos: [
      "SME0340,4",
      "SME0341,1",
      "SME0340,2",
      "SME0104,1",
      "SME0205,1",
      "SME0221,1",
      "SME0620,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0130",
    nome: "Redes Complexas",
    curso: "BECD, CEE, BCDados",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0130",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "17:00",
        fim: "19:00",
      },
      {
        dia: "Qua.",
        inicio: "17:00",
        fim: "19:00",
      },
    ],
    id: "SME0130,1",
    conflitos: [
      "SME0818,1",
      "SME0243,1",
      "SME0340,2",
      "SME0300,4",
      "SME0305,1",
      "SME0273,1",
      "SME0280,1",
      "SME0300,3",
    ],
    noturna: false,
  },
  {
    codigo: "SME0202",
    nome: "Métodos Numéricos em Equações Diferenciais",
    curso: "BMA, BMACC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0202",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Qua.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0202,1",
    conflitos: [
      "SME0300,2",
      "SME0610,1",
      "SME0340,3",
      "SME0230,1",
      "SME0602,1",
      "SME0340,6",
      "SME0340,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0202",
    nome: "Métodos Numéricos em Equações Diferenciais",
    curso: "BMACC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0202",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "14:20",
        fim: "16:00",
      },
      {
        dia: "Ter.",
        inicio: "14:20",
        fim: "16:00",
      },
    ],
    id: "SME0202,1",
    conflitos: [
      "SME0320,2",
      "SME0340,5",
      "SME0320,1",
      "SME0320,3",
      "SME0602,1",
      "SME0852,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0205",
    nome: "Métodos do Cálculo Numérico I",
    curso: "BMA, LMA, BMACC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0205",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Qui.",
        inicio: "08:10",
        fim: "09:50",
      },
    ],
    id: "SME0205,1",
    conflitos: [
      "SME0300,2",
      "SME0333,1",
      "SME0121,2",
      "SME0104,1",
      "SME0121,1",
      "SME0620,1",
      "SME0104,2",
    ],
    noturna: false,
  },
  {
    codigo: "SME0216",
    nome: "Tópicos de Otimização Combinatória",
    curso: "BMACC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0216",
    nivel: "g",
    horarios: [
      {
        dia: "Qui.",
        inicio: "14:20",
        fim: "16:00",
      },
      {
        dia: "Qui.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0216,1",
    conflitos: [
      "SME0346,1",
      "SME0340,5",
      "SME0320,3",
      "5500004,1",
      "SME0852,1",
      "SME0340,6",
      "SME0341,2",
      "SME0320,4",
    ],
    noturna: false,
  },
  {
    codigo: "SME0221",
    nome: "Introdução à Inferência Estatística",
    curso: "BCDados, BMACC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0221",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Qui.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0221,1",
    conflitos: [
      "SME0340,4",
      "SME0341,1",
      "SME0121,2",
      "SME0340,2",
      "SME0104,1",
      "SME0860,1",
      "SME0121,1",
      "SME0104,2",
      "5500004,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0230",
    nome: "Introdução à Programação de Computadores",
    curso: "MAT-NG, BMACC",
    turma: 1,
    carga: 1.5,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0230",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Qua.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0230,1",
    conflitos: [
      "SME0300,2",
      "SME0610,1",
      "SME0340,3",
      "SME0602,1",
      "SME0202,1",
      "SME0340,6",
      "SME0340,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0243",
    nome: "Teoria Espectral de Matrizes",
    curso: "BMACC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0243",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "16:20",
        fim: "18:00",
      },
      {
        dia: "Qua.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0243,1",
    conflitos: [
      "SME0130,1",
      "SME0340,2",
      "SME0300,4",
      "SME0305,1",
      "SME0273,1",
      "SME0280,1",
      "SME0300,3",
    ],
    noturna: false,
  },
  {
    codigo: "SME0273",
    nome: "Prática em Matemática Aplicada e Computação Científica",
    curso: "BMACC",
    turma: 1,
    carga: 0.5,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0273",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "16:20",
        fim: "18:00",
      },
      {
        dia: "Ter.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0273,1",
    conflitos: [
      "SME0130,1",
      "SME0243,1",
      "SME0340,2",
      "SME0300,4",
      "SME0305,1",
      "SME0300,3",
      "SME0320,4",
    ],
    noturna: false,
  },
  {
    codigo: "SME0280",
    nome: "Acompanhamento Profissional",
    curso: "BMACC",
    turma: 1,
    carga: 0.5,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0280",
    nivel: "g",
    horarios: [
      {
        dia: "Qua.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0280,1",
    conflitos: ["SME0130,1", "SME0243,1", "SME0300,4"],
    noturna: false,
  },
  {
    codigo: "SME0284",
    nome: "Estágio Supervisionado",
    curso: "BMACC",
    turma: 1,
    carga: 0.25,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0284",
    nivel: "g",
    horarios: [
      {
        dia: "Sex.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Sex.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0284,1",
    conflitos: ["SME0285,1", "SME0340,1", "SME0300,1", "SME0305,1"],
    noturna: false,
  },
  {
    codigo: "SME0285",
    nome: "Trabalho de Conclusão de Curso",
    curso: "BMACC",
    turma: 1,
    carga: 0.25,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0285",
    nivel: "g",
    horarios: [
      {
        dia: "Sex.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Sex.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0285,1",
    conflitos: ["SME0305,1", "SME0340,1", "SME0300,1", "SME0284,1"],
    noturna: false,
  },
  {
    codigo: "SME0300",
    nome: "Cálculo Numérico",
    curso: "Mecânica",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0300",
    nivel: "g",
    horarios: [
      {
        dia: "Qua.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Sex.",
        inicio: "08:10",
        fim: "09:50",
      },
    ],
    id: "SME0300,1",
    conflitos: ["SME0285,1", "SME0305,2", "SME0340,1", "SME0284,1"],
    noturna: false,
  },
  {
    codigo: "SME0300",
    nome: "Cálculo Numérico",
    curso: "Aeronáutica",
    turma: 2,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0300",
    nivel: "g",
    horarios: [
      {
        dia: "Qua.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Qui.",
        inicio: "08:10",
        fim: "09:50",
      },
    ],
    id: "SME0300,2",
    conflitos: [
      "SME0333,1",
      "SME0610,1",
      "SME0340,3",
      "SME0230,1",
      "SME0205,1",
      "SME0121,1",
      "SME0602,1",
      "SME0202,1",
      "SME0620,1",
      "SME0104,2",
      "SME0340,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0300",
    nome: "Cálculo Numérico",
    curso: "Produção",
    turma: 3,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0300",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "16:20",
        fim: "18:00",
      },
      {
        dia: "Qua.",
        inicio: "14:20",
        fim: "16:00",
      },
    ],
    id: "SME0300,3",
    conflitos: [
      "SME0320,2",
      "SME0130,1",
      "SME0320,1",
      "SME0243,1",
      "SME0340,2",
      "SME0300,4",
      "SME0305,1",
      "SME0273,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0300",
    nome: "Cálculo Numérico",
    curso: "Mecatrônica",
    turma: 4,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0300",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "16:20",
        fim: "18:00",
      },
      {
        dia: "Qua.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0300,4",
    conflitos: [
      "SME0130,1",
      "SME0243,1",
      "SME0340,2",
      "SME0305,1",
      "SME0273,1",
      "SME0280,1",
      "SME0300,3",
    ],
    noturna: false,
  },
  {
    codigo: "SME0305",
    nome: "Métodos Numéricos e Computacionais I",
    curso: "Civil",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0305",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "16:20",
        fim: "18:00",
      },
      {
        dia: "Sex.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0305,1",
    conflitos: [
      "SME0285,1",
      "SME0284,1",
      "SME0130,1",
      "SME0243,1",
      "SME0340,2",
      "SME0300,4",
      "SME0273,1",
      "SME0300,3",
    ],
    noturna: false,
  },
  {
    codigo: "SME0305",
    nome: "Métodos Numéricos e Computacionais I",
    curso: "Materiais",
    turma: 2,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0305",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Qua.",
        inicio: "08:10",
        fim: "09:50",
      },
    ],
    id: "SME0305,2",
    conflitos: ["SME0300,1"],
    noturna: false,
  },
  {
    codigo: "SME0320",
    nome: "Estatística I",
    curso: "Eletrônica",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0320",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "14:20",
        fim: "16:00",
      },
      {
        dia: "Qua.",
        inicio: "14:20",
        fim: "16:00",
      },
    ],
    id: "SME0320,1",
    conflitos: ["SME0300,3", "SME0202,1", "SME0602,1", "SME0320,2"],
    noturna: false,
  },
  {
    codigo: "SME0320",
    nome: "Estatística I",
    curso: "Automação",
    turma: 2,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0320",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "14:20",
        fim: "16:00",
      },
      {
        dia: "Qua.",
        inicio: "14:20",
        fim: "16:00",
      },
    ],
    id: "SME0320,2",
    conflitos: ["SME0300,3", "SME0202,1", "SME0320,1", "SME0602,1"],
    noturna: false,
  },
  {
    codigo: "SME0320",
    nome: "Estatística I",
    curso: "Mecânica",
    turma: 3,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0320",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "14:20",
        fim: "16:00",
      },
      {
        dia: "Qui.",
        inicio: "14:20",
        fim: "16:00",
      },
    ],
    id: "SME0320,3",
    conflitos: [
      "SME0346,1",
      "SME0340,5",
      "SME0216,1",
      "SME0202,1",
      "SME0852,1",
      "SME0341,2",
      "5500004,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0320",
    nome: "Estatística I",
    curso: "Produção",
    turma: 4,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0320",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "16:20",
        fim: "18:00",
      },
      {
        dia: "Qui.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0320,4",
    conflitos: ["SME0216,1", "SME0340,6", "SME0273,1", "SME0852,1"],
    noturna: false,
  },
  {
    codigo: "SME0333",
    nome: "Computação numérica e simulações para Engenharia Ambiental I",
    curso: "Ambiental",
    turma: 1,
    carga: 0.5,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0333",
    nivel: "g",
    horarios: [
      {
        dia: "Qui.",
        inicio: "08:10",
        fim: "09:50",
      },
    ],
    id: "SME0333,1",
    conflitos: [
      "SME0300,2",
      "SME0205,1",
      "SME0121,1",
      "SME0620,1",
      "SME0104,2",
    ],
    noturna: false,
  },
  {
    codigo: "SME0340",
    nome: "Equações Diferenciais Ordinárias",
    curso: "Eletrônica",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0340",
    nivel: "g",
    horarios: [
      {
        dia: "Qua.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Sex.",
        inicio: "08:10",
        fim: "09:50",
      },
    ],
    id: "SME0340,1",
    conflitos: [
      "SME0285,1",
      "SME0300,2",
      "SME0284,1",
      "SME0610,1",
      "SME0340,3",
      "SME0230,1",
      "SME0602,1",
      "SME0202,1",
      "SME0300,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0340",
    nome: "Equações Diferenciais Ordinárias",
    curso: "Automação",
    turma: 2,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0340",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "16:20",
        fim: "18:00",
      },
      {
        dia: "Qui.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0340,2",
    conflitos: [
      "SME0340,4",
      "SME0341,1",
      "SME0121,2",
      "SME0130,1",
      "SME0243,1",
      "SME0300,4",
      "SME0104,1",
      "SME0305,1",
      "SME0273,1",
      "SME0221,1",
      "SME0300,3",
    ],
    noturna: false,
  },
  {
    codigo: "SME0340",
    nome: "Equações Diferenciais Ordinárias",
    curso: "Mecânica",
    turma: 3,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0340",
    nivel: "g",
    horarios: [
      {
        dia: "Qua.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Sex.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0340,3",
    conflitos: [
      "SME0300,2",
      "SME0341,1",
      "SME0610,1",
      "SME0230,1",
      "SME0602,1",
      "SME0202,1",
      "SME0341,2",
      "SME0340,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0340",
    nome: "Equações Diferenciais Ordinárias",
    curso: "Aeronáutica",
    turma: 4,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0340",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Qui.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0340,4",
    conflitos: [
      "SME0341,1",
      "SME0121,2",
      "SME0340,2",
      "SME0104,1",
      "SME0860,1",
      "SME0121,1",
      "SME0221,1",
      "SME0104,2",
      "5500004,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0340",
    nome: "Equações Diferenciais Ordinárias",
    curso: "Mecatrônica",
    turma: 5,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0340",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "14:20",
        fim: "16:00",
      },
      {
        dia: "Qui.",
        inicio: "14:20",
        fim: "16:00",
      },
    ],
    id: "SME0340,5",
    conflitos: [
      "SME0346,1",
      "SME0320,3",
      "SME0216,1",
      "SME0202,1",
      "SME0852,1",
      "SME0341,2",
      "5500004,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0340",
    nome: "Equações Diferenciais Ordinárias",
    curso: "Eng. Computação",
    turma: 6,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0340",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Qui.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0340,6",
    conflitos: [
      "SME0610,1",
      "SME0230,1",
      "SME0216,1",
      "SME0852,1",
      "SME0202,1",
      "SME0320,4",
    ],
    noturna: false,
  },
  {
    codigo: "SME0341",
    nome: "Álgebra Linear e Equações Diferenciais",
    curso: "Ambiental",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0341",
    nivel: "g",
    horarios: [
      {
        dia: "Qui.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Sex.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0341,1",
    conflitos: [
      "SME0340,4",
      "SME0121,2",
      "SME0340,2",
      "SME0104,1",
      "SME0340,3",
      "SME0221,1",
      "SME0341,2",
    ],
    noturna: false,
  },
  {
    codigo: "SME0341",
    nome: "Álgebra Linear e Equações Diferenciais",
    curso: "Materiais",
    turma: 2,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0341",
    nivel: "g",
    horarios: [
      {
        dia: "Qui.",
        inicio: "14:20",
        fim: "16:00",
      },
      {
        dia: "Sex.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0341,2",
    conflitos: [
      "SME0341,1",
      "SME0346,1",
      "SME0340,5",
      "SME0320,3",
      "SME0340,3",
      "SME0216,1",
      "5500004,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0346",
    nome: "Matemática para Arquitetura",
    curso: "Arquitetura",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0346",
    nivel: "g",
    horarios: [
      {
        dia: "Qui.",
        inicio: "14:20",
        fim: "16:00",
      },
      {
        dia: "Sex.",
        inicio: "14:20",
        fim: "16:00",
      },
    ],
    id: "SME0346,1",
    conflitos: [
      "SME0340,5",
      "SME0320,3",
      "SME0216,1",
      "SME0341,2",
      "5500004,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0500",
    nome: "Cálculo Numérico",
    curso: "BSI",
    turma: 1,
    carga: 0.5,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0500",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "19:00",
        fim: "20:40",
      },
    ],
    id: "SME0500,1",
    conflitos: ["SME0816,1", "SME0818,1"],
    noturna: true,
  },
  {
    codigo: "SME0520",
    nome: "Introdução à Estatística",
    curso: "BSI",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0520",
    nivel: "g",
    horarios: [
      {
        dia: "Qui.",
        inicio: "19:00",
        fim: "20:40",
      },
      {
        dia: "Sex.",
        inicio: "21:00",
        fim: "22:40",
      },
    ],
    id: "SME0520,1",
    conflitos: [
      "SME0825,1",
      "SLC0609,1",
      "SME0821,1",
      "SME0829,1",
      "SME0878,1",
      "SME0827,1",
    ],
    noturna: true,
  },
  {
    codigo: "SME0602",
    nome: "Cálculo Numérico",
    curso: "Eng. Computação",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0602",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "14:20",
        fim: "16:00",
      },
      {
        dia: "Qua.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0602,1",
    conflitos: [
      "SME0320,2",
      "SME0300,2",
      "SME0320,1",
      "SME0610,1",
      "SME0340,3",
      "SME0230,1",
      "SME0202,1",
      "SME0340,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0610",
    nome: "Programação Matemática",
    curso: "Eng. Computação",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0610",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "10:10",
        fim: "11:50",
      },
      {
        dia: "Qua.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0610,1",
    conflitos: [
      "SME0300,2",
      "SME0340,3",
      "SME0230,1",
      "SME0602,1",
      "SME0202,1",
      "SME0340,6",
      "SME0340,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0620",
    nome: "Estatística I",
    curso: "Eng. Computação",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0620",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Qui.",
        inicio: "08:10",
        fim: "09:50",
      },
    ],
    id: "SME0620,1",
    conflitos: [
      "SME0300,2",
      "SME0333,1",
      "SME0121,2",
      "SME0104,1",
      "SME0205,1",
      "SME0121,1",
      "SME0104,2",
    ],
    noturna: false,
  },
  {
    codigo: "SME0801",
    nome: "Probabilidade II",
    curso: "BECD",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0801",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "21:00",
        fim: "22:40",
      },
      {
        dia: "Qui.",
        inicio: "21:00",
        fim: "22:40",
      },
    ],
    id: "SME0801,1",
    conflitos: ["SME0806,1", "SME0816,1"],
    noturna: true,
  },
  {
    codigo: "SME0803",
    nome: "Visualização e Exploração de Dados",
    curso: "BECD, BCDados",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0803",
    nivel: "g",
    horarios: [
      {
        dia: "Qua.",
        inicio: "21:00",
        fim: "22:40",
      },
      {
        dia: "Sex.",
        inicio: "19:00",
        fim: "20:40",
      },
    ],
    id: "SME0803,1",
    conflitos: [
      "SME0806,1",
      "SLC0609,1",
      "SME0892,1",
      "SME0829,1",
      "SME0878,1",
    ],
    noturna: true,
  },
  {
    codigo: "SME0806",
    nome: "Estatística Computacional",
    curso: "BECD, BCDados",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0806",
    nivel: "g",
    horarios: [
      {
        dia: "Qui.",
        inicio: "21:00",
        fim: "22:40",
      },
      {
        dia: "Sex.",
        inicio: "19:00",
        fim: "20:40",
      },
    ],
    id: "SME0806,1",
    conflitos: ["SME0892,1", "SME0801,1", "SME0803,1", "SLC0609,1"],
    noturna: true,
  },
  {
    codigo: "SME0807",
    nome: "Técnicas de Amostragem",
    curso: "BECD",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0807",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "21:00",
        fim: "22:40",
      },
      {
        dia: "Ter.",
        inicio: "19:00",
        fim: "20:40",
      },
    ],
    id: "SME0807,1",
    conflitos: ["SME0825,1"],
    noturna: true,
  },
  {
    codigo: "SME0814",
    nome: "Estágio Supervisionado em Estatística I",
    curso: "BECD",
    turma: 1,
    carga: 0.25,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0814",
    nivel: "g",
    horarios: [
      {
        dia: "Sáb.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Sáb.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0814,1",
    conflitos: ["SME0880,1", "SME0815,1", "SME0881,1"],
    noturna: false,
  },
  {
    codigo: "SME0815",
    nome: "Estágio Supervisionado em Estatística II",
    curso: "BECD",
    turma: 1,
    carga: 0.25,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0815",
    nivel: "g",
    horarios: [
      {
        dia: "Sáb.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Sáb.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0815,1",
    conflitos: ["SME0880,1", "SME0814,1", "SME0881,1"],
    noturna: false,
  },
  {
    codigo: "SME0816",
    nome: "Planejamento de Experimentos I",
    curso: "BECD",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0816",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "19:00",
        fim: "20:40",
      },
      {
        dia: "Ter.",
        inicio: "21:00",
        fim: "22:40",
      },
    ],
    id: "SME0816,1",
    conflitos: ["SME0500,1", "SME0801,1", "SME0818,1"],
    noturna: true,
  },
  {
    codigo: "SME0818",
    nome: "Inferência Estatística",
    curso: "BECD",
    turma: 1,
    carga: 1.5,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0818",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "18:00",
        fim: "20:40",
      },
      {
        dia: "Qua.",
        inicio: "18:00",
        fim: "20:40",
      },
    ],
    id: "SME0818,1",
    conflitos: ["SME0500,1", "SME0130,1", "SME0821,1", "SME0816,1"],
    noturna: true,
  },
  {
    codigo: "SME0821",
    nome: "Análise de Sobrevivência e Confiabilidade",
    curso: "BECD",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0821",
    nivel: "g",
    horarios: [
      {
        dia: "Qua.",
        inicio: "19:00",
        fim: "20:40",
      },
      {
        dia: "Sex.",
        inicio: "21:00",
        fim: "22:40",
      },
    ],
    id: "SME0821,1",
    conflitos: ["SME0520,1", "SME0818,1", "SLC0609,1"],
    noturna: true,
  },
  {
    codigo: "SME0825",
    nome: "Metodologia Científica I",
    curso: "BECD",
    turma: 1,
    carga: 0.5,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0825",
    nivel: "g",
    horarios: [
      {
        dia: "Seg.",
        inicio: "21:00",
        fim: "22:40",
      },
      {
        dia: "Qui.",
        inicio: "19:00",
        fim: "20:40",
      },
    ],
    id: "SME0825,1",
    conflitos: [
      "SME0520,1",
      "SME0807,1",
      "SME0829,1",
      "SME0878,1",
      "SME0827,1",
    ],
    noturna: true,
  },
  {
    codigo: "SME0827",
    nome: "Estruturas de Dados",
    curso: "BECD",
    turma: 1,
    carga: 0.75,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0827",
    nivel: "g",
    horarios: [
      {
        dia: "Qui.",
        inicio: "18:00",
        fim: "20:40",
      },
    ],
    id: "SME0827,1",
    conflitos: [
      "SME0520,1",
      "SME0825,1",
      "SME0890,1",
      "SME0829,1",
      "SME0878,1",
    ],
    noturna: true,
  },
  {
    codigo: "SME0829",
    nome: "Aprendizado de Máquina",
    curso: "BECD",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0829",
    nivel: "g",
    horarios: [
      {
        dia: "Qua.",
        inicio: "21:00",
        fim: "22:40",
      },
      {
        dia: "Qui.",
        inicio: "19:00",
        fim: "20:40",
      },
    ],
    id: "SME0829,1",
    conflitos: [
      "SME0520,1",
      "SME0825,1",
      "SME0892,1",
      "SME0878,1",
      "SME0827,1",
      "SME0803,1",
    ],
    noturna: true,
  },
  {
    codigo: "SME0830",
    nome: "Probabilidade I (modalidade semipresencial)",
    curso: "BECD",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0830",
    nivel: "g",
    horarios: [],
    id: "SME0830,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "SME0852",
    nome: "Prática em Ciência de Dados I",
    curso: "BCDados, BECD",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0852",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "14:20",
        fim: "16:00",
      },
      {
        dia: "Qui.",
        inicio: "16:20",
        fim: "18:00",
      },
    ],
    id: "SME0852,1",
    conflitos: [
      "SME0340,5",
      "SME0320,3",
      "SME0216,1",
      "SME0202,1",
      "SME0340,6",
      "SME0320,4",
    ],
    noturna: false,
  },
  {
    codigo: "SME0860",
    nome: "Aprendizado de Máquina Aplicado a Problemas",
    curso: "BCDados",
    turma: 1,
    carga: 0.5,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0860",
    nivel: "g",
    horarios: [
      {
        dia: "Ter.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0860,1",
    conflitos: [
      "SME0340,4",
      "SME0121,1",
      "SME0221,1",
      "SME0104,2",
      "5500004,1",
    ],
    noturna: false,
  },
  {
    codigo: "SME0871",
    nome: "Bioestatística",
    curso: "BCDados",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0871",
    nivel: "g",
    horarios: [],
    id: "SME0871,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "SME0878",
    nome: "Mineração Estatística de Dados",
    curso: "BCDados, BECD, BSI",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0878",
    nivel: "g",
    horarios: [
      {
        dia: "Qua.",
        inicio: "21:00",
        fim: "22:40",
      },
      {
        dia: "Qui.",
        inicio: "19:00",
        fim: "20:40",
      },
    ],
    id: "SME0878,1",
    conflitos: [
      "SME0520,1",
      "SME0825,1",
      "SME0892,1",
      "SME0829,1",
      "SME0803,1",
      "SME0827,1",
    ],
    noturna: true,
  },
  {
    codigo: "SME0880",
    nome: "Projeto de Graduação em Estatística I",
    curso: "BECD",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0880",
    nivel: "g",
    horarios: [
      {
        dia: "Sáb.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Sáb.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0880,1",
    conflitos: ["SME0814,1", "SME0815,1", "SME0881,1"],
    noturna: false,
  },
  {
    codigo: "SME0881",
    nome: "Projeto de Graduação em Estatística II",
    curso: "BECD",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0881",
    nivel: "g",
    horarios: [
      {
        dia: "Sáb.",
        inicio: "08:10",
        fim: "09:50",
      },
      {
        dia: "Sáb.",
        inicio: "10:10",
        fim: "11:50",
      },
    ],
    id: "SME0881,1",
    conflitos: ["SME0880,1", "SME0814,1", "SME0815,1"],
    noturna: false,
  },
  {
    codigo: "SME0890",
    nome: "Direcionamento Acadêmico I",
    curso: "BECD",
    turma: 1,
    carga: 0.25,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0890",
    nivel: "g",
    horarios: [
      {
        dia: "Qui.",
        inicio: "18:00",
        fim: "18:50",
      },
    ],
    id: "SME0890,1",
    conflitos: ["SME0827,1"],
    noturna: true,
  },
  {
    codigo: "SME0892",
    nome: "Cálculo Numérico para Estatística",
    curso: "BECD",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=SME0892",
    nivel: "g",
    horarios: [
      {
        dia: "Qua.",
        inicio: "21:00",
        fim: "22:40",
      },
      {
        dia: "Sex.",
        inicio: "19:00",
        fim: "20:40",
      },
    ],
    id: "SME0892,1",
    conflitos: [
      "SME0806,1",
      "SLC0609,1",
      "SME0829,1",
      "SME0878,1",
      "SME0803,1",
    ],
    noturna: true,
  },
  {
    codigo: "SME5781",
    nome: "Álgebra Linear Aplicada",
    curso: "CCMC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=SME5781",
    nivel: "p",
    horarios: [],
    id: "SME5781,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "SME5784",
    nome: "Métodos Numéricos para Equações Diferenciais",
    curso: "CCMC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=SME5784",
    nivel: "p",
    horarios: [],
    id: "SME5784,1",
    conflitos: [],
    noturna: false,
  },
  {
    codigo: "SME5826",
    nome: "Tópicos em Otimização",
    curso: "CCMC",
    turma: 1,
    carga: 1.0,
    grupo: "",
    ementa:
      "https://www.icmc.usp.br/pos-graduacao/disciplinas?programa=55134&disciplina=SME5826",
    nivel: "p",
    horarios: [],
    id: "SME5826,1",
    conflitos: [],
    noturna: false,
  },
];
